#pragma once
#include <stdint.h>

enum {
    SYSCALL_WRITE = 1,
    SYSCALL_EXIT = 2, 
    SYSCALL_EXEC = 3,
    SYSCALL_GETCHAR = 4,
    SYSCALL_CLEAR = 5,
    SYSCALL_WRITEFILE = 6,
    SYSCALL_LISTFILES = 7,
    SYSCALL_READFILE = 8,
    SYSCALL_GETARG = 9,
    SYSCALL_PUT_AT = 10,
    SYSCALL_SETCURSOR = 11,
    SYSCALL_TRYGETCHAR = 12,
    SYSCALL_GETTICKS = 13,
    SYSCALL_SLEEP = 14,
    SYSCALL_GETSIZE = 15,
    SYSCALL_BLIT = 16,
    SYSCALL_MOUSE_GET = 17,
    SYSCALL_MOUSE_SHOW= 18,
    SYSCALL_ENUMFILES = 19,
    SYSCALL_GFX_INFO = 20,
    SYSCALL_GFX_CLEAR = 21,
    SYSCALL_GFX_PUTPX = 22,
    SYSCALL_GFX_BLIT = 23,
    SYSCALL_THEME_SET = 24,
    SYSCALL_THEME_GET = 25,
};

void syscall_init(void);
